#define GLFW_INCLUDE_NONE
#ifndef INPUTMANAGER_H
#define INPUTMANAGER_H

#include <GLFW/glfw3.h>

#include "Camera.h"
#include "SceneDefinition.h"

struct InputActions
{
        /** Toggle scripted/manual camera mode. */
        bool toggleCameraMode;
        /** Toggle info overlay visibility. */
        bool toggleInfoOverlay;
        /** Toggle simulation pause state. */
        bool togglePause;
        /** Step simulation time forward by fixed increment. */
        bool stepTimeForward;
        /** Step simulation time backward by fixed increment. */
        bool stepTimeBackward;
};

/**
 * @brief Handles user input, camera control, and action toggles for the
 * application.
 */
class InputManager
{
    public:
        /**
         * @brief Construct an InputManager with the given input configuration.
         * @param inputConfig Input configuration struct.
         */
        explicit InputManager(const InputConfig& inputConfig);
        ~InputManager();

        /**
         * @brief Register this manager instance as GLFW callback target.
         */
        void registerAsCallbackTarget();
        /**
         * @brief Set camera instance for input-driven movement and rotation.
         * @param cameraPtr Pointer to the camera to control.
         */
        void setCamera(Camera* cameraPtr);
        /**
         * @brief Enable or disable camera controls (WASD + mouse look).
         * @param enabled True to enable, false to disable.
         */
        void setCameraControlEnabled(bool enabled);
        /**
         * @brief Process per-frame keyboard input.
         * @param window GLFW window pointer.
         * @param deltaTime Frame delta time.
         */
        void processInput(GLFWwindow* window, float deltaTime);
        /**
         * @brief Consume pending action toggles generated by processInput.
         * @return Struct containing toggled actions.
         */
        InputActions consumeActions();

        /**
         * @brief Resize callback that updates OpenGL viewport.
         * @param window GLFW window pointer.
         * @param width New width.
         * @param height New height.
         */
        static void framebufferSizeCallback(GLFWwindow* window, int width,
                                            int height);
        /**
         * @brief Mouse-move callback for camera look updates.
         * @param window GLFW window pointer.
         * @param xposIn Mouse X position.
         * @param yposIn Mouse Y position.
         */
        static void mouseCallback(GLFWwindow* window, double xposIn,
                                  double yposIn);
        /**
         * @brief Mouse-wheel callback for camera zoom updates.
         * @param window GLFW window pointer.
         * @param xoffset Mouse wheel X offset.
         * @param yoffset Mouse wheel Y offset.
         */
        static void scrollCallback(GLFWwindow* window, double xoffset,
                                   double yoffset);

    private:
        static InputManager* callbackTarget;

        float        lastX;
        float        lastY;
        bool         firstMouse;
        bool         cameraControlEnabled;
        bool         cameraModeToggleLatch;
        bool         infoOverlayToggleLatch;
        bool         pauseToggleLatch;
        bool         stepForwardLatch;
        bool         stepBackwardLatch;
        InputActions pendingActions;
        InputConfig  inputConfig;
        Camera*      camera;
};

#endif
