#define GLFW_INCLUDE_NONE
#ifndef INPUTMANAGER_H
#define INPUTMANAGER_H

#include <GLFW/glfw3.h>

#include "Camera.h"

class InputManager
{
public:
	/** @brief Set camera instance for input-driven movement and rotation. */
	static void setCamera(Camera *cameraPtr);
	/** @brief Enable or disable camera controls (WASD + mouse look). */
	static void setCameraControlEnabled(bool enabled);
	/** @brief Process per-frame keyboard input. */
	static void processInput(GLFWwindow *window, float deltaTime);
	/** @brief Consume pending camera mode toggle request generated by processInput. */
	static bool consumeCameraModeToggleRequest();
	/** @brief Consume pending info overlay toggle request generated by processInput. */
	static bool consumeInfoOverlayToggleRequest();

	/** @brief Resize callback that updates OpenGL viewport. */
	static void framebufferSizeCallback(GLFWwindow *window, int width, int height);
	/** @brief Mouse-move callback for camera look updates. */
	static void mouseCallback(GLFWwindow *window, double xposIn, double yposIn);
	/** @brief Mouse-wheel callback for camera zoom updates. */
	static void scrollCallback(GLFWwindow *window, double xoffset, double yoffset);

private:
	static float lastX;
	static float lastY;
	static bool firstMouse;
	static bool cameraControlEnabled;
	static bool cameraModeToggleLatch;
	static bool infoOverlayToggleLatch;
	static bool cameraModeToggleRequested;
	static bool infoOverlayToggleRequested;
	static Camera *camera;
};

#endif
